// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJQgY_5hFyjvNd85o444Dl2-f0ZotJ0A',
    appId: '1:16557475056:web:3305e5299ec9741cf96e35',
    messagingSenderId: '16557475056',
    projectId: 'farmernekt',
    authDomain: 'farmernekt.firebaseapp.com',
    storageBucket: 'farmernekt.appspot.com',
    measurementId: 'G-1YXML3EQBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGIS_rywxlmGat_gSgrYJnvur02e7ZXo8',
    appId: '1:16557475056:android:af3389b6076ad9c4f96e35',
    messagingSenderId: '16557475056',
    projectId: 'farmernekt',
    storageBucket: 'farmernekt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj__kmHKF1J-2bLmXYL1f5H-IO3vc-2HM',
    appId: '1:16557475056:ios:2dcddf104729df77f96e35',
    messagingSenderId: '16557475056',
    projectId: 'farmernekt',
    storageBucket: 'farmernekt.appspot.com',
    iosBundleId: 'com.example.farmernekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj__kmHKF1J-2bLmXYL1f5H-IO3vc-2HM',
    appId: '1:16557475056:ios:2dcddf104729df77f96e35',
    messagingSenderId: '16557475056',
    projectId: 'farmernekt',
    storageBucket: 'farmernekt.appspot.com',
    iosBundleId: 'com.example.farmernekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJQgY_5hFyjvNd85o444Dl2-f0ZotJ0A',
    appId: '1:16557475056:web:034f26c330b9c559f96e35',
    messagingSenderId: '16557475056',
    projectId: 'farmernekt',
    authDomain: 'farmernekt.firebaseapp.com',
    storageBucket: 'farmernekt.appspot.com',
    measurementId: 'G-FS9PZMCF3S',
  );
}
